title: MIP Materials
description: MIP Materials documentation
theme: just-the-docs

url: https://just-the-docs.github.io

# Damit Seiten aus dem Ordner 'wmc/' korrekt verarbeitet werden
collections:
  wmc:
    output: true
    permalink: /:collection/:path/
    name: "WMC"

# Navigationsstruktur optional anpassbar (nur bei Bedarf)
# just_the_docs:
#   collections:
#     wmc:
#       name: "WMC"
#       nav_order: 2
